packages:
  - analysis
  - site
  - 'packages/*'

autoInstallPeers: false
allowBuilds:
  esbuild: true
  sharp: true
overrides:
  'vitepress>@docsearch/js': '-'
  "vitepress>@docsearch/sidepanel-js": "-"
