packages:
  - analysis
  - site
  - 'packages/*'

autoInstallPeers: false
allowBuilds:
  esbuild: true
  sharp: true
overrides:
  prettier: $prettier
  'vitepress>@docsearch/js': '-'
  'vitepress>vite': '^8.0.10'
