name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
      - 'pnpm-lock.yaml'
      - '!**/*.md'
  pull_request:
    paths:
      - 'packages/**'
      - '.github/workflows/ci.yml'
      - 'pnpm-lock.yaml'
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  # https://github.com/nodejs/corepack/issues/612#issuecomment-2631462297
  # Corepack is only used in tests. This isn't required for other workflows.
  # This sets the old and new integrity keys for corepack to download different
  # package managers signed with different keys.
  COREPACK_INTEGRITY_KEYS: '{"npm":[{"expires":"2025-01-29T00:00:00.000Z","keyid":"SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1Olb3zMAFFxXKHiIkQO5cJ3Yhl5i6UPp+IhuteBJbuHcA5UogKo0EWtlWwW6KSaKoTNEYL7JlCQiVnkhBktUgg=="},{"expires":null,"keyid":"SHA256:DhQ8wR5APBvFHLF/+Tc+AYvPOdTpcIDqOhxsBHRwC7U","keytype":"ecdsa-sha2-nistp256","scheme":"ecdsa-sha2-nistp256","key":"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEY6Ya7W++7aUPzvMTrezH6Ycx3c+HOKYCcNGybJZSCJq/fd7Qa8uuAKtdIkUQtQiEKERhAmE5lMMJhP8OkDOa2g=="}]}'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Technically we need to test node 18 and 20 too, but our tooling no longer support it.
        # We'll rely on user reports for now.
        node: [22, 24, 26]
        include:
          - os: windows-latest
            node: 22
      fail-fast: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}

      # Bun is only used in tests. This isn't required for other workflows.
      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install dependencies
        run: pnpm install

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 24 }}
        name: Lint
        run: pnpm lint

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 24 }}
        name: Typecheck
        run: pnpm typecheck

      - if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 24 }}
        name: Lint with publint
        run: pnpm lint-publint

      - name: Run tests
        run: pnpm test
